/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFileChooser;

/**
 *
 * @author Chris
 */
public class frmMecanico extends javax.swing.JFrame {

    /**
     * Creates new form frmMarca
     */
    public frmMecanico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEst = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btgSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnValEmple = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumDocEmp = new javax.swing.JTextField();
        rdbEstA = new javax.swing.JRadioButton();
        rdbEstI = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaObsEmp = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtNomEmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboDocEmp = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtApeEmp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboCiuEmp = new javax.swing.JComboBox<>();
        rdbSexM = new javax.swing.JRadioButton();
        rdbSexF = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cod. Mecanico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnValEmple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValEmple.setText(">>>");
        btnValEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValEmpleActionPerformed(evt);
            }
        });
        jPanel1.add(btnValEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtNumDocEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumDocEmp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumDocEmp.setText("1030538949");
        txtNumDocEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDocEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 100, -1));

        rdbEstA.setBackground(new java.awt.Color(204, 204, 255));
        btgEst.add(rdbEstA);
        rdbEstA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbEstA.setText("Activo");
        rdbEstA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEstAActionPerformed(evt);
            }
        });
        jPanel1.add(rdbEstA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        rdbEstI.setBackground(new java.awt.Color(204, 204, 255));
        btgEst.add(rdbEstI);
        rdbEstI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbEstI.setText("Inactivo");
        jPanel1.add(rdbEstI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 20));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txaObsEmp.setColumns(20);
        txaObsEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaObsEmp.setRows(5);
        txaObsEmp.setPreferredSize(new java.awt.Dimension(320, 104));
        jScrollPane1.setViewportView(txaObsEmp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 440, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Observaciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtNomEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomEmp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomEmp.setText("CHRISIAN CAMILO");
        txtNomEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 87, 270, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombres");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 90, -1, -1));

        txtCodEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodEmpleado.setText("1030538949");
        jPanel1.add(txtCodEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Num. Documento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        cboDocEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboDocEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDocEmpActionPerformed(evt);
            }
        });
        jPanel1.add(cboDocEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Apellidos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 120, -1, -1));

        txtApeEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApeEmp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApeEmp.setText("GUTIERREZ MONTOYA");
        txtApeEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtApeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ciudad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        cboCiuEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboCiuEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCiuEmpActionPerformed(evt);
            }
        });
        jPanel1.add(cboCiuEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 210, -1));

        rdbSexM.setBackground(new java.awt.Color(204, 204, 255));
        btgSexo.add(rdbSexM);
        rdbSexM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbSexM.setText("Masculino");
        rdbSexM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSexMActionPerformed(evt);
            }
        });
        jPanel1.add(rdbSexM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, 20));

        rdbSexF.setBackground(new java.awt.Color(204, 204, 255));
        btgSexo.add(rdbSexF);
        rdbSexF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbSexF.setText("Femenino");
        jPanel1.add(rdbSexF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 198, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 163, 50));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\new_file_28px.png")); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNuevo);

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\edit_file_28px.png")); // NOI18N
        btnEditar.setToolTipText("Modificar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\undo_28px.png")); // NOI18N
        btnCancelar.setToolTipText("Deshacer");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCancelar);

        btnBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\delete_file_28px.png")); // NOI18N
        btnBorrar.setToolTipText("Eliminar");
        btnBorrar.setFocusable(false);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBorrar);

        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\view_file_28px.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBuscar);

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\save_28px.png")); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnGuardar);

        btnCargar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\circled_up_2_28px.png")); // NOI18N
        btnCargar.setToolTipText("Cargar");
        btnCargar.setFocusable(false);
        btnCargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCargar);

        btnImprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\print_28px.png")); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnImprimir);

        btnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\shutdown_28px.png")); // NOI18N
        btnCerrar.setToolTipText("Salir");
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCerrar);

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opciones");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Herramientas");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbEstAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEstAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEstAActionPerformed

    private void txtNomEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomEmpActionPerformed

    private void txtNumDocEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocEmpActionPerformed

    private void btnValEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValEmpleActionPerformed

    private void cboDocEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDocEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDocEmpActionPerformed

    private void txtApeEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeEmpActionPerformed

    private void cboCiuEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCiuEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCiuEmpActionPerformed

    private void rdbSexMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSexMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSexMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgEst;
    public javax.swing.ButtonGroup btgSexo;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCargar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnImprimir;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnValEmple;
    public javax.swing.JComboBox<String> cboCiuEmp;
    public javax.swing.JComboBox<String> cboDocEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JToolBar jToolBar1;
    public javax.swing.JRadioButton rdbEstA;
    public javax.swing.JRadioButton rdbEstI;
    public javax.swing.JRadioButton rdbSexF;
    public javax.swing.JRadioButton rdbSexM;
    public javax.swing.JTextArea txaObsEmp;
    public javax.swing.JTextField txtApeEmp;
    public javax.swing.JTextField txtCodEmpleado;
    public javax.swing.JTextField txtNomEmp;
    public javax.swing.JTextField txtNumDocEmp;
    // End of variables declaration//GEN-END:variables

}
