/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFileChooser;

/**
 *
 * @author Chris
 */
public class frmOrdenTra extends javax.swing.JFrame {

    /**
     * Creates new form frmMarca
     */
    public frmOrdenTra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEst = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btgSexo = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgrRep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDetOrden = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtModeloCarro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMarcaCarro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescRepuesto = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCodOrden = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMotorCarro = new javax.swing.JTextField();
        txtNomCliente = new javax.swing.JTextField();
        txtCodRepuesto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTipoRep = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUndRep = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        spnCantRep = new javax.swing.JSpinner();
        btnValPlaca = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jftFecOrden = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbOrdenRep = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtCodEmple = new javax.swing.JTextField();
        txtNomEmple = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaObsOrden = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\new_file_28px.png")); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNuevo);

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\edit_file_28px.png")); // NOI18N
        btnEditar.setToolTipText("Modificar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\undo_28px.png")); // NOI18N
        btnCancelar.setToolTipText("Deshacer");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCancelar);

        btnBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\delete_file_28px.png")); // NOI18N
        btnBorrar.setToolTipText("Eliminar");
        btnBorrar.setFocusable(false);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBorrar);

        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\view_file_28px.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBuscar);

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\save_28px.png")); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnGuardar);

        btnCargar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\circled_up_2_28px.png")); // NOI18N
        btnCargar.setToolTipText("Cargar");
        btnCargar.setFocusable(false);
        btnCargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCargar);

        btnImprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\print_28px.png")); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnImprimir);

        btnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\shutdown_28px.png")); // NOI18N
        btnCerrar.setToolTipText("Salir");
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCerrar);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Placa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnAgrRep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgrRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_checkmark_16px.png"))); // NOI18N
        btnAgrRep.setText("Agregar");
        btnAgrRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrRepActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgrRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 255, 100, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txaDetOrden.setColumns(20);
        txaDetOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaDetOrden.setRows(5);
        txaDetOrden.setPreferredSize(new java.awt.Dimension(320, 104));
        jScrollPane1.setViewportView(txaDetOrden);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 393, 630, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Trabajo Realizado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtModeloCarro.setBackground(new java.awt.Color(204, 204, 204));
        txtModeloCarro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtModeloCarro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloCarroActionPerformed(evt);
            }
        });
        jPanel1.add(txtModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Modelo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Marca");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtMarcaCarro.setBackground(new java.awt.Color(204, 204, 204));
        txtMarcaCarro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMarcaCarro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMarcaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaCarroActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nombre");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 72, -1, -1));

        txtDescRepuesto.setBackground(new java.awt.Color(204, 204, 204));
        txtDescRepuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescRepuestoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 480, -1));

        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 630, 40));

        txtCodOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodOrden.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodOrdenActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 10, 120, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("No. Orden");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Telefono");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 72, -1, -1));

        txtTelCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtTelCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 72, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 630, 70));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Motor");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        txtMotorCarro.setBackground(new java.awt.Color(204, 204, 204));
        txtMotorCarro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotorCarro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMotorCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotorCarroActionPerformed(evt);
            }
        });
        jPanel1.add(txtMotorCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 140, -1));

        txtNomCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtNomCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 72, 350, -1));

        txtCodRepuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodRepuesto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRepuestoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tipo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 255, -1, -1));

        txtTipoRep.setBackground(new java.awt.Color(204, 204, 204));
        txtTipoRep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTipoRep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoRepActionPerformed(evt);
            }
        });
        jPanel1.add(txtTipoRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 255, 190, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Und. Disp");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 255, -1, -1));

        txtUndRep.setBackground(new java.awt.Color(204, 204, 204));
        txtUndRep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUndRep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUndRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUndRepActionPerformed(evt);
            }
        });
        jPanel1.add(txtUndRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 255, 60, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Repuesto");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        spnCantRep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(spnCantRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 255, 50, -1));

        btnValPlaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValPlaca.setText(">>>");
        btnValPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(btnValPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("FechaOrden");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jftFecOrden.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jftFecOrden.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftFecOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jftFecOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 100, -1));

        jtbOrdenRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtbOrdenRep);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 540, 70));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Mecánico");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 175, -1, -1));

        txtCodEmple.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodEmple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodEmpleActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 175, 100, -1));

        txtNomEmple.setBackground(new java.awt.Color(204, 204, 204));
        txtNomEmple.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEmpleActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 175, 360, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 630, 45));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Observaciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txaObsOrden.setColumns(20);
        txaObsOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaObsOrden.setRows(5);
        txaObsOrden.setPreferredSize(new java.awt.Dimension(320, 104));
        jScrollPane4.setViewportView(txaObsOrden);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 630, 50));

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opciones");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Herramientas");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloCarroActionPerformed

    private void btnAgrRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgrRepActionPerformed

    private void txtMarcaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaCarroActionPerformed

    private void txtDescRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescRepuestoActionPerformed

    private void txtCodOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodOrdenActionPerformed

    private void txtTelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelClienteActionPerformed

    private void txtMotorCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotorCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotorCarroActionPerformed

    private void txtNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomClienteActionPerformed

    private void txtCodRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRepuestoActionPerformed

    private void txtTipoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoRepActionPerformed

    private void txtUndRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUndRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUndRepActionPerformed

    private void btnValPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValPlacaActionPerformed

    private void txtCodEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodEmpleActionPerformed

    private void txtNomEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomEmpleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrdenTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrdenTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrdenTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrdenTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrdenTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgEst;
    public javax.swing.ButtonGroup btgSexo;
    public javax.swing.JButton btnAgrRep;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCargar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnImprimir;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnValPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    public javax.swing.JToolBar jToolBar1;
    public javax.swing.JFormattedTextField jftFecOrden;
    public javax.swing.JTable jtbOrdenRep;
    public javax.swing.JSpinner spnCantRep;
    public javax.swing.JTextArea txaDetOrden;
    public javax.swing.JTextArea txaObsOrden;
    public javax.swing.JTextField txtCodEmple;
    public javax.swing.JTextField txtCodOrden;
    public javax.swing.JTextField txtCodRepuesto;
    public javax.swing.JTextField txtDescRepuesto;
    public javax.swing.JTextField txtMarcaCarro;
    public javax.swing.JTextField txtModeloCarro;
    public javax.swing.JTextField txtMotorCarro;
    public javax.swing.JTextField txtNomCliente;
    public javax.swing.JTextField txtNomEmple;
    public javax.swing.JFormattedTextField txtPlaca;
    public javax.swing.JTextField txtTelCliente;
    public javax.swing.JTextField txtTipoRep;
    public javax.swing.JTextField txtUndRep;
    // End of variables declaration//GEN-END:variables

}
