/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFileChooser;

/**
 *
 * @author Chris
 */
public class frmRepuesto extends javax.swing.JFrame {

    /**
     * Creates new form frmMarca
     */
    public frmRepuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgRepu = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantRepu = new javax.swing.JTextField();
        btnValRepu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomRepu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdbRepuAct = new javax.swing.JRadioButton();
        rdbRepuIna = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaObsRepu = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbDataRepu = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtDesRepu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodRepu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboTipoRepu = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cod. Repuesto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 12, -1, -1));

        txtCantRepu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantRepu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 155, 50, -1));

        btnValRepu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValRepu.setText(">>>");
        btnValRepu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValRepuActionPerformed(evt);
            }
        });
        jPanel1.add(btnValRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipo Repuesto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 84, -1, -1));

        txtNomRepu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomRepu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomRepu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomRepuActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 45, 320, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Estado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 157, -1, -1));

        rdbRepuAct.setBackground(new java.awt.Color(204, 204, 255));
        btgRepu.add(rdbRepuAct);
        rdbRepuAct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbRepuAct.setText("Activo");
        rdbRepuAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRepuActActionPerformed(evt);
            }
        });
        jPanel1.add(rdbRepuAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 158, -1, 20));

        rdbRepuIna.setBackground(new java.awt.Color(204, 204, 255));
        btgRepu.add(rdbRepuIna);
        rdbRepuIna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbRepuIna.setText("Inactivo");
        jPanel1.add(rdbRepuIna, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 158, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Datos Existentes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txaObsRepu.setColumns(20);
        txaObsRepu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaObsRepu.setRows(5);
        txaObsRepu.setPreferredSize(new java.awt.Dimension(320, 104));
        jScrollPane1.setViewportView(txaObsRepu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 320, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Observaciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jtbDataRepu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtbDataRepu);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 420, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Stock");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 157, -1, -1));

        txtDesRepu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDesRepu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDesRepu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesRepuActionPerformed(evt);
            }
        });
        jPanel1.add(txtDesRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Descr. Repuesto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 122, -1, -1));

        txtCodRepu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodRepu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCodRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nom. Repuesto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, -1, -1));

        cboTipoRepu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTipoRepu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoRepuActionPerformed(evt);
            }
        });
        jPanel1.add(cboTipoRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 82, 170, -1));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\new_file_28px.png")); // NOI18N
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNuevo);

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\edit_file_28px.png")); // NOI18N
        btnEditar.setToolTipText("Modificar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\undo_28px.png")); // NOI18N
        btnCancelar.setToolTipText("Deshacer");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCancelar);

        btnBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\delete_file_28px.png")); // NOI18N
        btnBorrar.setToolTipText("Eliminar");
        btnBorrar.setFocusable(false);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBorrar);

        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\view_file_28px.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBuscar);

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\save_28px.png")); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnGuardar);

        btnCargar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\circled_up_2_28px.png")); // NOI18N
        btnCargar.setToolTipText("Cargar");
        btnCargar.setFocusable(false);
        btnCargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCargar);

        btnImprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\print_28px.png")); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnImprimir);

        btnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Documentos\\Java-Projects\\SistemaAutos\\img\\shutdown_28px.png")); // NOI18N
        btnCerrar.setToolTipText("Salir");
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCerrar);

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opciones");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Herramientas");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbRepuActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRepuActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbRepuActActionPerformed

    private void txtDesRepuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesRepuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesRepuActionPerformed

    private void txtNomRepuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomRepuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomRepuActionPerformed

    private void btnValRepuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValRepuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValRepuActionPerformed

    private void cboTipoRepuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoRepuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoRepuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRepuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgRepu;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCargar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnImprimir;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnValRepu;
    public javax.swing.JComboBox<String> cboTipoRepu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable jtbDataRepu;
    public javax.swing.JRadioButton rdbRepuAct;
    public javax.swing.JRadioButton rdbRepuIna;
    public javax.swing.JTextArea txaObsRepu;
    public javax.swing.JTextField txtCantRepu;
    public javax.swing.JTextField txtCodRepu;
    public javax.swing.JTextField txtDesRepu;
    public javax.swing.JTextField txtNomRepu;
    // End of variables declaration//GEN-END:variables

}
