/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.vCliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.fCliente;

/**
 *
 * @author Chris
 */
public class frmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProducto
     */
    public frmCliente() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setTitle("Clientes");
        Mostrar("");
        Inhabilitar();
    }

    private String Accion = "Guardar";

    void OcultarCols() {
        tblListaClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblListaClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblListaClientes.getColumnModel().getColumn(0).setPreferredWidth(0);;
    }

    void Inhabilitar() {
        txtNomCliente.setEnabled(false);
        txtPrimApeCliente.setEnabled(false);
        txtSegApeCliente.setEnabled(false);
        cboTipDocCliente.setEnabled(false);
        txtNumDocCliente.setEnabled(false);
        txtDireCliente.setEnabled(false);
        txtTelCliente.setEnabled(false);
        txtMailCliente.setEnabled(false);
        txtCodCliente.setEnabled(false);
        txtIDcliente.setVisible(false);
        
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnBorrar.setEnabled(false);

        txtNomCliente.setText("");
        txtPrimApeCliente.setText("");
        txtSegApeCliente.setText("");
        cboTipDocCliente.setSelectedIndex(0);
        txtNumDocCliente.setText("");
        txtDireCliente.setText("");
        txtTelCliente.setText("");
        txtMailCliente.setText("");
        txtCodCliente.setText("");
        txtIDcliente.setText("");

    }

    void Habilitar() {
        txtNomCliente.setEnabled(true);
        txtPrimApeCliente.setEnabled(true);
        txtSegApeCliente.setEnabled(true);
        cboTipDocCliente.setEnabled(true);
        txtNumDocCliente.setEnabled(true);
        txtDireCliente.setEnabled(true);
        txtTelCliente.setEnabled(true);
        txtMailCliente.setEnabled(true);
        txtCodCliente.setEnabled(true);
        txtIDcliente.setVisible(false);

        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnBorrar.setEnabled(true);

        txtNomCliente.setText("");
        txtPrimApeCliente.setText("");
        txtSegApeCliente.setText("");
        cboTipDocCliente.setSelectedIndex(0);
        txtNumDocCliente.setText("");
        txtDireCliente.setText("");
        txtTelCliente.setText("");
        txtMailCliente.setText("");
        txtCodCliente.setText("");
        txtIDcliente.setText("");

    }
    
    void Mostrar(String buscar) {
        try {
            DefaultTableModel fModelo;
            fCliente nFuncion = new fCliente();
            fModelo = nFuncion.mostrar(buscar);
            tblListaClientes.setModel(fModelo);
            OcultarCols();
            lblTotalReg.setText("Total Filas: " + Integer.toString(nFuncion.totFilas));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtIDcliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumDocCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboTipDocCliente = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMailCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSegApeCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNomCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrimApeCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTotalReg = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Cliente");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDcliente.setBackground(new java.awt.Color(255, 255, 255));
        txtIDcliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(txtIDcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 30, -1, -1));

        txtTelCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtTelCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtTelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Número:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        txtNumDocCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNumDocCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtNumDocCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDocCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Tipo Documento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cboTipDocCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cboTipDocCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          --- Selecione ---", "CEDULA DE CIUDADANIA", "PASAPORTE", "CEDULA EXTRANJERIA", "CEDULA MILITAR" }));
        cboTipDocCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipDocClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cboTipDocCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 90, 200, -1));

        btnNuevo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_plus_16px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 79, 30));

        btnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_save_16px_1.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 79, 30));

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_close_window_16px_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 79, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Primer Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, -1, -1));

        txtMailCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtMailCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtMailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtMailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 150, 447, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Segundo Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txtCodCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtCodCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 180, 210, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 120, -1, -1));

        txtDireCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtDireCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtDireCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 120, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 120, -1, -1));

        txtSegApeCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtSegApeCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtSegApeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegApeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtSegApeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtNomCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 30, 447, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Cod. Cliente:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 180, -1, -1));

        txtPrimApeCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimApeCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtPrimApeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimApeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrimApeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 60, 160, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblListaClientes.setBackground(new java.awt.Color(255, 255, 255));
        tblListaClientes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaClientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblListaClientes);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, 471, 160));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Buscar:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 31, 136, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_search_more_16px_2.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 28, 79, 30));

        btnBorrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_delete_16px.png"))); // NOI18N
        btnBorrar.setText("Eliminar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 28, 79, 30));

        btnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_export_16px.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 28, 79, 30));

        lblTotalReg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblTotalReg.setText("Registros:");
        jPanel2.add(lblTotalReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelClienteActionPerformed
        // TODO add your handling code here:
        txtTelCliente.transferFocus();
    }//GEN-LAST:event_txtTelClienteActionPerformed

    private void txtNumDocClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocClienteActionPerformed
        // TODO add your handling code here:
        txtNumDocCliente.transferFocus();
    }//GEN-LAST:event_txtNumDocClienteActionPerformed

    private void cboTipDocClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipDocClienteActionPerformed
        // TODO add your handling code here:
        cboTipDocCliente.transferFocus();
    }//GEN-LAST:event_cboTipDocClienteActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        btnGuardar.setText("Guardar");
        Accion = "Guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNomCliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            txtNomCliente.requestFocus();
            return;
        }
        if (txtPrimApeCliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            txtPrimApeCliente.requestFocus();
            return;
        }
        if (txtSegApeCliente.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            txtSegApeCliente.requestFocus();
            return;
        }
        if (cboTipDocCliente.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            cboTipDocCliente.requestFocus();
            return;
        }
        if (txtNumDocCliente.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            txtNumDocCliente.requestFocus();
            return;
        }
        if (txtTelCliente.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            txtTelCliente.requestFocus();
            return;
        }
        if (txtCodCliente.getText().length()==0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Cliente", JOptionPane.WARNING_MESSAGE);
            txtCodCliente.requestFocus();
            return;
        }
        

        vCliente fDatCliente = new vCliente();
        fCliente nFunCliente = new fCliente();

        fDatCliente.setNomPers(txtNomCliente.getText());
        fDatCliente.setPrapePers(txtPrimApeCliente.getText());
        fDatCliente.setSegapePers(txtSegApeCliente.getText());
        fDatCliente.setTipdocPers(String.valueOf(cboTipDocCliente.getSelectedItem()));
        fDatCliente.setNumdocPers(txtNumDocCliente.getText());
        fDatCliente.setDirePers(txtDireCliente.getText());
        fDatCliente.setTelPers(txtTelCliente.getText());
        fDatCliente.setEmailPers(txtMailCliente.getText());
        fDatCliente.setCodCliente(txtCodCliente.getText());
        
        if (Accion.equals("Guardar")) {
            if (nFunCliente.GuardarCliente(fDatCliente)) {
                JOptionPane.showMessageDialog(this, "Cliente Guardado Correctamente", "Cliente", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }

        } else if (Accion.equals("Editar")) {
            fDatCliente.setIdPers(Integer.valueOf(txtIDcliente.getText()));
            if (nFunCliente.EditarCliente(fDatCliente)) {
                JOptionPane.showMessageDialog(this, "Edición Realizada Correctamente", "Cliente", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaClientesMouseClicked
        // TODO add your handling code here:
        btnGuardar.setText("Editar");
        Habilitar();
        btnBorrar.setEnabled(true);
        Accion = "Editar";

        int tFila = tblListaClientes.rowAtPoint(evt.getPoint());
        txtIDcliente.setText(tblListaClientes.getValueAt(tFila, 0).toString());
        txtNomCliente.setText(tblListaClientes.getValueAt(tFila, 1).toString());
        txtPrimApeCliente.setText(tblListaClientes.getValueAt(tFila, 2).toString());
        txtSegApeCliente.setText(tblListaClientes.getValueAt(tFila, 3).toString());
        cboTipDocCliente.setSelectedItem(tblListaClientes.getValueAt(tFila, 4).toString());
        txtNumDocCliente.setText(tblListaClientes.getValueAt(tFila, 5).toString());
        txtDireCliente.setText(tblListaClientes.getValueAt(tFila, 6).toString());
        txtTelCliente.setText(tblListaClientes.getValueAt(tFila, 7).toString());        
        txtMailCliente.setText(tblListaClientes.getValueAt(tFila, 8).toString());
        txtCodCliente.setText(tblListaClientes.getValueAt(tFila, 9).toString());
    }//GEN-LAST:event_tblListaClientesMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese un criterio", "Producto", JOptionPane.WARNING_MESSAGE);
            txtBuscar.requestFocus();
            return;
        } else {
            Mostrar(txtBuscar.getText());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if (!txtIDcliente.getText().equals("")) {
            int Confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar el Cliente?", "Confirmar", 2);
            if (Confirmar == 0) {
                fCliente nFunCliente = new fCliente();
                vCliente fDatCliente = new vCliente();

                fDatCliente.setIdPers(Integer.parseInt(txtIDcliente.getText()));
                nFunCliente.BorrarCliente(fDatCliente);
                JOptionPane.showMessageDialog(this, "Registro Borrado", "Cliente", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Cliente", JOptionPane.WARNING_MESSAGE);
            tblListaClientes.requestFocus();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Desea cerrar el formulario?", "Cliente",
                    JOptionPane.ERROR_MESSAGE,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtMailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailClienteActionPerformed
        // TODO add your handling code here:
        txtMailCliente.transferFocus();
    }//GEN-LAST:event_txtMailClienteActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:
        txtCodCliente.transferFocus();
    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void txtDireClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireClienteActionPerformed
        // TODO add your handling code here:
        txtDireCliente.transferFocus();
    }//GEN-LAST:event_txtDireClienteActionPerformed

    private void txtSegApeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegApeClienteActionPerformed
        // TODO add your handling code here:
        txtSegApeCliente.transferFocus();
    }//GEN-LAST:event_txtSegApeClienteActionPerformed

    private void txtNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomClienteActionPerformed
        // TODO add your handling code here:
        txtNomCliente.transferFocus();
    }//GEN-LAST:event_txtNomClienteActionPerformed

    private void txtPrimApeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimApeClienteActionPerformed
        // TODO add your handling code here:
        txtPrimApeCliente.transferFocus();
    }//GEN-LAST:event_txtPrimApeClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboTipDocCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotalReg;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtDireCliente;
    private javax.swing.JTextField txtIDcliente;
    private javax.swing.JTextField txtMailCliente;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtNumDocCliente;
    private javax.swing.JTextField txtPrimApeCliente;
    private javax.swing.JTextField txtSegApeCliente;
    private javax.swing.JTextField txtTelCliente;
    // End of variables declaration//GEN-END:variables
}
