/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.vConsumo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.fConsumo;

/**
 *
 * @author Chris
 */
public class frmConsumo extends javax.swing.JInternalFrame {

    public static String codRsva;
    public static String Cliente;

    /**
     * Creates new form frmConsumo
     */
    public frmConsumo() {
        initComponents();
        Mostrar(codRsva);
        txtIDreserva.setText(codRsva);
        txtNomCliente.setText(Cliente);
        Inhabilitar();
    }

    private String Accion = "Guardar";

    void OcultarCols() {
        tblConsuListado.getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsuListado.getColumnModel().getColumn(0).setMinWidth(0);
        tblConsuListado.getColumnModel().getColumn(0).setPreferredWidth(0);

        tblConsuListado.getColumnModel().getColumn(1).setMaxWidth(0);
        tblConsuListado.getColumnModel().getColumn(1).setMinWidth(0);
        tblConsuListado.getColumnModel().getColumn(1).setPreferredWidth(0);

        tblConsuListado.getColumnModel().getColumn(2).setMaxWidth(0);
        tblConsuListado.getColumnModel().getColumn(2).setMinWidth(0);
        tblConsuListado.getColumnModel().getColumn(2).setPreferredWidth(0);
    }

    void Inhabilitar() {
        txtIDconsumo.setVisible(false);
        txtIDreserva.setVisible(false);
        txtIDproducto.setVisible(false);

        txtNomCliente.setEnabled(false);
        txtNomProdu.setEnabled(false);
        spnCantidad.setEnabled(false);
        txtPreVenta.setEnabled(false);
        cboEstConsu.setEnabled(false);

        btnBusqProd.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnBorrar.setEnabled(false);

        txtIDconsumo.setText("");
        //txtIDreserva.setText("");
        txtIDproducto.setText("");
        //txtNomCliente.setText("");
        txtNomProdu.setText("");
        spnCantidad.setValue(0);
        txtPreVenta.setText("");
        cboEstConsu.setSelectedIndex(0);

    }

    void Habilitar() {
        txtIDconsumo.setVisible(false);
        txtIDreserva.setVisible(false);
        txtIDproducto.setVisible(false);

        txtNomCliente.setEnabled(true);
        txtNomProdu.setEnabled(true);
        spnCantidad.setEnabled(true);
        txtPreVenta.setEnabled(true);
        cboEstConsu.setEnabled(true);

        btnBusqProd.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnBorrar.setEnabled(true);

        txtIDconsumo.setText("");
        //txtIDreserva.setText("");
        txtIDproducto.setText("");
        //txtNomCliente.setText("");
        txtNomProdu.setText("");
        spnCantidad.setValue(0);
        txtPreVenta.setText("");
        cboEstConsu.setSelectedIndex(0);
    }

    void Mostrar(String buscar) {
        try {
            DefaultTableModel fModelo;
            fConsumo nFunConsu = new fConsumo();
            fModelo = nFunConsu.mostrar(buscar);
            tblConsuListado.setModel(fModelo);
            OcultarCols();
            lblTotalReg.setText("Total Filas: " + Integer.toString(nFunConsu.totFilas));
            lblTotalConsu.setText("Total ($): " + Double.toString(nFunConsu.totConsumo));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtIDconsumo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPreVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboEstConsu = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtIDreserva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIDproducto = new javax.swing.JTextField();
        txtNomProdu = new javax.swing.JTextField();
        btnBusqProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsuListado = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTotalConsu = new javax.swing.JLabel();
        lblTotalReg = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Consumo");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Consumo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDconsumo.setBackground(new java.awt.Color(255, 255, 255));
        txtIDconsumo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(txtIDconsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 126, 45, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Reserva:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 30, -1, -1));

        txtNomCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Precio Venta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 95, -1, -1));

        txtPreVenta.setEditable(false);
        txtPreVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtPreVenta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtPreVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPreVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 95, 126, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 126, -1, -1));

        cboEstConsu.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cboEstConsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          --- Selecione ---", "ACEPTADO", "CANCELADO" }));
        cboEstConsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstConsuActionPerformed(evt);
            }
        });
        jPanel1.add(cboEstConsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 126, 200, -1));

        btnNuevo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_plus_16px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 79, 30));

        btnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_save_16px_1.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 160, 79, 30));

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_close_window_16px_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 79, 30));

        txtIDreserva.setBackground(new java.awt.Color(255, 255, 255));
        txtIDreserva.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtIDreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDreservaActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 126, 45, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 95, -1, -1));

        txtIDproducto.setBackground(new java.awt.Color(255, 255, 255));
        txtIDproducto.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtIDproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDproductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 45, -1));

        txtNomProdu.setEditable(false);
        txtNomProdu.setBackground(new java.awt.Color(204, 204, 204));
        txtNomProdu.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtNomProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProduActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 63, 260, -1));

        btnBusqProd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBusqProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_search_more_16px_2.png"))); // NOI18N
        btnBusqProd.setText("...");
        btnBusqProd.setToolTipText("Buscar Producto");
        btnBusqProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBusqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusqProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusqProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 63, 40, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Producto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 63, -1, -1));

        spnCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 95, 50, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado Consumos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblConsuListado.setBackground(new java.awt.Color(255, 255, 255));
        tblConsuListado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblConsuListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsuListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsuListadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblConsuListado);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, 471, 100));

        btnBorrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_delete_16px.png"))); // NOI18N
        btnBorrar.setText("Eliminar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 28, 79, 30));

        btnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_export_16px.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 28, 79, 30));

        lblTotalConsu.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblTotalConsu.setText("Total ($):");
        jPanel2.add(lblTotalConsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 150, -1));

        lblTotalReg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblTotalReg.setText("Registros:");
        jPanel2.add(lblTotalReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomClienteActionPerformed
        // TODO add your handling code here:
        txtNomCliente.transferFocus();
    }//GEN-LAST:event_txtNomClienteActionPerformed

    private void txtPreVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreVentaActionPerformed
        // TODO add your handling code here:
        txtPreVenta.transferFocus();
    }//GEN-LAST:event_txtPreVentaActionPerformed

    private void cboEstConsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstConsuActionPerformed
        // TODO add your handling code here:
        cboEstConsu.transferFocus();
    }//GEN-LAST:event_cboEstConsuActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        btnGuardar.setText("Guardar");
        Accion = "Guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNomCliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Consumo", JOptionPane.WARNING_MESSAGE);
            txtNomCliente.requestFocus();
            return;
        }
        if (txtNomProdu.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Consumo", JOptionPane.WARNING_MESSAGE);
            txtNomProdu.requestFocus();
            return;
        }
        if (spnCantidad.getValue().equals(0)) {
            JOptionPane.showMessageDialog(this, "Cantidad Incorrecta", "Consumo", JOptionPane.WARNING_MESSAGE);
            spnCantidad.requestFocus();
            return;
        }
        if (cboEstConsu.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Datos Incompletos", "Consumo", JOptionPane.WARNING_MESSAGE);
            cboEstConsu.requestFocus();
            return;
        }

        vConsumo fDatosConsu = new vConsumo();
        fConsumo nFunConsu = new fConsumo();

        fDatosConsu.setId_RsvaConsu(Integer.valueOf(txtIDreserva.getText()));
        fDatosConsu.setId_ProdConsu(Integer.valueOf(txtIDproducto.getText()));
        fDatosConsu.setCantConsu(Integer.valueOf(spnCantidad.getValue().toString()));
        fDatosConsu.setPreVenConsu(Double.valueOf(txtPreVenta.getText()));
        fDatosConsu.setEstConsu(String.valueOf(cboEstConsu.getSelectedItem()));

        if (Accion.equals("Guardar")) {
            if (nFunConsu.GuardarConsu(fDatosConsu)) {
                JOptionPane.showMessageDialog(this, "Consumo Guardado Correctamente", "Consumo", JOptionPane.INFORMATION_MESSAGE);
                Mostrar(codRsva);
                Inhabilitar();
            }

        } else if (Accion.equals("Editar")) {
            fDatosConsu.setIdConsu(Integer.valueOf(txtIDconsumo.getText()));
            if (nFunConsu.EditarConsu(fDatosConsu)) {
                JOptionPane.showMessageDialog(this, "Edición Realizada Correctamente", "Consumo", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblConsuListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsuListadoMouseClicked
        // TODO add your handling code here:
        btnGuardar.setText("Editar");
        Habilitar();
        btnBorrar.setEnabled(true);
        Accion = "Editar";

        int tFila = tblConsuListado.rowAtPoint(evt.getPoint());
        txtIDconsumo.setText(tblConsuListado.getValueAt(tFila, 0).toString());
        txtIDreserva.setText(tblConsuListado.getValueAt(tFila, 1).toString());
        txtIDproducto.setText(tblConsuListado.getValueAt(tFila, 2).toString());
        txtNomProdu.setText(tblConsuListado.getValueAt(tFila, 3).toString());
        spnCantidad.setValue(Integer.valueOf(tblConsuListado.getValueAt(tFila, 4).toString()));
        txtPreVenta.setText(tblConsuListado.getValueAt(tFila, 5).toString());
        cboEstConsu.setSelectedItem(tblConsuListado.getValueAt(tFila, 6).toString());
        

    }//GEN-LAST:event_tblConsuListadoMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if (!txtIDconsumo.getText().equals("")) {
            int Confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar el Consumo?", "Confirmar", 2);
            if (Confirmar == 0) {
                fConsumo nFunConsu = new fConsumo();
                vConsumo fDatosConsu = new vConsumo();

                fDatosConsu.setIdConsu(Integer.parseInt(txtIDconsumo.getText()));
                nFunConsu.BorrarConsu(fDatosConsu);
                JOptionPane.showMessageDialog(this, "Registro Borrado", "Consumo", JOptionPane.INFORMATION_MESSAGE);
                Mostrar(codRsva);
                Inhabilitar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Consumo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Desea cerrar el formulario?", "Consumo",
                JOptionPane.ERROR_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtIDreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDreservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDreservaActionPerformed

    private void txtIDproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDproductoActionPerformed

    private void txtNomProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProduActionPerformed

    private void btnBusqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusqProdActionPerformed
        // TODO add your handling code here:
        frmVistaProdu nForma = new frmVistaProdu();
        nForma.toFront();
        nForma.setVisible(true);
    }//GEN-LAST:event_btnBusqProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusqProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboEstConsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotalConsu;
    private javax.swing.JLabel lblTotalReg;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblConsuListado;
    private javax.swing.JTextField txtIDconsumo;
    public static javax.swing.JTextField txtIDproducto;
    private javax.swing.JTextField txtIDreserva;
    public static javax.swing.JTextField txtNomCliente;
    public static javax.swing.JTextField txtNomProdu;
    public static javax.swing.JTextField txtPreVenta;
    // End of variables declaration//GEN-END:variables
}
