/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.vProducto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.fProducto;

/**
 *
 * @author Chris
 */
public class frmProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProducto
     */
    public frmProducto() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setTitle("Productos");
        Mostrar("");
        Inhabilitar();
    }

    private String Accion = "Guardar";

    void OcultarCols() {
        tblProdListado.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProdListado.getColumnModel().getColumn(0).setMinWidth(0);
        tblProdListado.getColumnModel().getColumn(0).setPreferredWidth(0);;
    }

    void Inhabilitar() {
        txtIDproducto.setVisible(false);
        cboUndMed.setEnabled(false);
        txtNomProd.setEnabled(false);
        txtDescProd.setEnabled(false);
        txtValVenta.setEnabled(false);

        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnBorrar.setEnabled(false);

        txtIDproducto.setText("");
        cboUndMed.setSelectedIndex(0);
        txtNomProd.setText("");
        txtDescProd.setText("");
        txtValVenta.setText("");

    }

    void Habilitar() {
        txtIDproducto.setVisible(false);
        cboUndMed.setEnabled(true);
        txtNomProd.setEnabled(true);
        txtDescProd.setEnabled(true);
        txtValVenta.setEnabled(true);

        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnBorrar.setEnabled(true);

        txtIDproducto.setText("");
        cboUndMed.setSelectedIndex(0);
        txtNomProd.setText("");
        txtDescProd.setText("");
        txtValVenta.setText("");

    }
    
    void Mostrar(String buscar) {
        try {
            DefaultTableModel fModelo;
            fProducto nFuncion = new fProducto();
            fModelo = nFuncion.mostrar(buscar);
            tblProdListado.setModel(fModelo);
            OcultarCols();
            lblTotalReg.setText("Total Filas: " + Integer.toString(nFuncion.totFilas));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtIDproducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescProd = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtValVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboUndMed = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdListado = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTotalReg = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Producto");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDproducto.setBackground(new java.awt.Color(255, 255, 255));
        txtIDproducto.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(txtIDproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 30, -1, -1));

        txtNomProd.setBackground(new java.awt.Color(255, 255, 255));
        txtNomProd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtNomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProdActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 320, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Descripcion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 63, -1, -1));

        txtDescProd.setBackground(new java.awt.Color(255, 255, 255));
        txtDescProd.setColumns(20);
        txtDescProd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtDescProd.setRows(5);
        jScrollPane2.setViewportView(txtDescProd);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 63, 321, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Valor Venta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 170, -1, -1));

        txtValVenta.setBackground(new java.awt.Color(255, 255, 255));
        txtValVenta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtValVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtValVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 126, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Und. Medida:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cboUndMed.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cboUndMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          --- Selecione ---", "KILOS", "UNIDADES", "LITROS", "MINUTOS", "GLOBAL" }));
        cboUndMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUndMedActionPerformed(evt);
            }
        });
        jPanel1.add(cboUndMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, -1));

        btnNuevo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_plus_16px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 79, 30));

        btnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_save_16px_1.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 79, 30));

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_close_window_16px_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 79, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProdListado.setBackground(new java.awt.Color(255, 255, 255));
        tblProdListado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblProdListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProdListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdListadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblProdListado);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, 471, 150));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Buscar:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 31, 136, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_search_more_16px_2.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 28, 79, 30));

        btnBorrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_delete_16px.png"))); // NOI18N
        btnBorrar.setText("Eliminar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 28, 79, 30));

        btnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_export_16px.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 28, 79, 30));

        lblTotalReg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblTotalReg.setText("Registros:");
        jPanel2.add(lblTotalReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProdActionPerformed
        // TODO add your handling code here:
        txtNomProd.transferFocus();
    }//GEN-LAST:event_txtNomProdActionPerformed

    private void txtValVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValVentaActionPerformed
        // TODO add your handling code here:
        txtValVenta.transferFocus();
    }//GEN-LAST:event_txtValVentaActionPerformed

    private void cboUndMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUndMedActionPerformed
        // TODO add your handling code here:
        cboUndMed.transferFocus();
    }//GEN-LAST:event_cboUndMedActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        btnGuardar.setText("Guardar");
        Accion = "Guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNomProd.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese el Nombre del Producto", "Producto", JOptionPane.WARNING_MESSAGE);
            txtNomProd.requestFocus();
            return;
        }
        if (txtDescProd.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese la Descripción del Producto", "Producto", JOptionPane.WARNING_MESSAGE);
            txtDescProd.requestFocus();
            return;
        }
        if (cboUndMed.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "Ingrese la Unidad de Medida del Producto", "Producto", JOptionPane.WARNING_MESSAGE);
            cboUndMed.requestFocus();
            return;
        }
        if (txtValVenta.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese el Valor del Producto", "Producto", JOptionPane.WARNING_MESSAGE);
            txtValVenta.requestFocus();
            return;
        }

        vProducto fDatosProd = new vProducto();
        fProducto nFuncionProd = new fProducto();

        fDatosProd.setNomProd(txtNomProd.getText());
        fDatosProd.setDescProd(txtDescProd.getText());
        fDatosProd.setUndmProd(String.valueOf(cboUndMed.getSelectedItem()));
        fDatosProd.setValvProd(Double.valueOf(txtValVenta.getText()));
        
        if (Accion.equals("Guardar")) {
            if (nFuncionProd.GuardarProd(fDatosProd)) {
                JOptionPane.showMessageDialog(this, "Producto Guardado Correctamente", "Producto", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }

        } else if (Accion.equals("Editar")) {
            fDatosProd.setIdProd(Integer.valueOf(txtIDproducto.getText()));
            if (nFuncionProd.EditarProd(fDatosProd)) {
                JOptionPane.showMessageDialog(this, "Edición Realizada Correctamente", "Producto", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblProdListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdListadoMouseClicked
        // TODO add your handling code here:
        btnGuardar.setText("Editar");
        Habilitar();
        btnBorrar.setEnabled(true);
        Accion = "Editar";

        int tFila = tblProdListado.rowAtPoint(evt.getPoint());
        txtIDproducto.setText(tblProdListado.getValueAt(tFila, 0).toString());
        txtNomProd.setText(tblProdListado.getValueAt(tFila, 1).toString());
        txtDescProd.setText(tblProdListado.getValueAt(tFila, 2).toString());
        cboUndMed.setSelectedItem(tblProdListado.getValueAt(tFila, 3).toString());
        txtValVenta.setText(tblProdListado.getValueAt(tFila, 4).toString());
        
    }//GEN-LAST:event_tblProdListadoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese un criterio", "Producto", JOptionPane.WARNING_MESSAGE);
            txtBuscar.requestFocus();
            return;
        } else {
            Mostrar(txtBuscar.getText());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if (!txtIDproducto.getText().equals("")) {
            int Confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar el Producto?", "Confirmar", 2);
            if (Confirmar == 0) {
                fProducto nFuncionProd = new fProducto();
                vProducto fDatosProd = new vProducto();

                fDatosProd.setIdProd(Integer.parseInt(txtIDproducto.getText()));
                nFuncionProd.BorrarProd(fDatosProd);
                JOptionPane.showMessageDialog(this, "Registro Borrado", "Producto", JOptionPane.INFORMATION_MESSAGE);
                Mostrar("");
                Inhabilitar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Producto", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Desea cerrar el formulario?", "Producto",
                    JOptionPane.ERROR_MESSAGE,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboUndMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotalReg;
    private javax.swing.JTable tblProdListado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescProd;
    private javax.swing.JTextField txtIDproducto;
    private javax.swing.JTextField txtNomProd;
    private javax.swing.JTextField txtValVenta;
    // End of variables declaration//GEN-END:variables
}
