/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlCiudad;
import controlador.ControlColor;
import controlador.ControlMarca;
import controlador.ControlOrdenTrab;
import controlador.ControlRepuesto;
import controlador.ControlTipo;
import modelo.Ciudad;
import modelo.CiudadCRUD;
import modelo.Cliente;
import modelo.Color;
import modelo.ColorCRUD;
import modelo.Marca;
import modelo.MarcaCRUD;
import modelo.OrdenTrab;
import modelo.OrdenTrabCRUD;
import modelo.Repuesto;
import modelo.RepuestoCRUD;
import modelo.Tipo;
import modelo.TipoCRUD;
import modelo.Vehiculo;

/**
 *
 * @author Chris
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setExtendedState(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCliente = new javax.swing.JMenu();
        mnuVehiculo = new javax.swing.JMenu();
        mnuOrdenT = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuMarca = new javax.swing.JMenuItem();
        jMenuColor = new javax.swing.JMenuItem();
        jMenuCiudades = new javax.swing.JMenuItem();
        jMenuTipos = new javax.swing.JMenuItem();
        mnuRepuesto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/motor.jpg"))); // NOI18N
        jLabel1.setLabelFor(this);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnuCliente.setText("Cliente");
        mnuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCliente);

        mnuVehiculo.setText("Vehiculo");
        mnuVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuVehiculoMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuVehiculo);

        mnuOrdenT.setText("Mantenimiento");
        mnuOrdenT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOrdenTMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuOrdenT);

        jMenu3.setText("Operaciones");

        mnuMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_porsche_16px.png"))); // NOI18N
        mnuMarca.setText("Marcas");
        mnuMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMarcaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMarca);

        jMenuColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_paint_palette_16px.png"))); // NOI18N
        jMenuColor.setText("Colores");
        jMenuColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuColorActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuColor);

        jMenuCiudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_europe_16px.png"))); // NOI18N
        jMenuCiudades.setText("Ciudades");
        jMenuCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCiudadesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCiudades);

        jMenuTipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_automatic_16px.png"))); // NOI18N
        jMenuTipos.setText("Tipos");
        jMenuTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTiposActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTipos);

        mnuRepuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_maintenance_16px.png"))); // NOI18N
        mnuRepuesto.setText("Repuestos");
        mnuRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepuestoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuRepuesto);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuClienteMouseClicked
        frmCliente frmCliente = new frmCliente();
        frmCliente.setVisible(true);
        frmCliente.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuClienteMouseClicked

    private void mnuVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuVehiculoMouseClicked
        frmVehiculo frmVehiculo = new frmVehiculo();
        frmVehiculo.setVisible(true);
        frmVehiculo.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuVehiculoMouseClicked

    private void mnuMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMarcaActionPerformed
        Marca appMarca = new Marca();
        MarcaCRUD appMarcaCRUD = new MarcaCRUD();
        frmMarca appFormaMarca = new frmMarca();
        frmMarcaTodo appFormaTodos = new frmMarcaTodo(appFormaMarca, true);
        ControlMarca appControlMarca = new ControlMarca(appMarca, appMarcaCRUD, appFormaMarca, appFormaTodos);
        appControlMarca.IniciarMarca();
        appFormaMarca.setVisible(true);
    }//GEN-LAST:event_mnuMarcaActionPerformed

    private void jMenuColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuColorActionPerformed
        Color appColor = new Color();
        ColorCRUD appColorCRUD = new ColorCRUD();
        frmColor appFormaColor = new frmColor();
        frmColorTodo appColorTodos = new frmColorTodo(appFormaColor, true);
        ControlColor appControlColor = new ControlColor(appColor, appColorCRUD, appFormaColor, appColorTodos);
        appControlColor.IniciarColor();
        appFormaColor.setVisible(true);
    }//GEN-LAST:event_jMenuColorActionPerformed

    private void jMenuCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCiudadesActionPerformed
        Ciudad appCiudad = new Ciudad();
        CiudadCRUD appCiudadCRUD = new CiudadCRUD();
        frmCiudad appFormaCiudad = new frmCiudad();
        frmCiudadTodo appCiudadTodos = new frmCiudadTodo(appFormaCiudad, true);
        ControlCiudad appControlCiudad = new ControlCiudad(appCiudad, appCiudadCRUD, appFormaCiudad, appCiudadTodos);
        appControlCiudad.IniciarCiudad();
        appFormaCiudad.setVisible(true);
    }//GEN-LAST:event_jMenuCiudadesActionPerformed

    private void jMenuTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTiposActionPerformed
        Tipo appTipo = new Tipo();
        TipoCRUD appTipoCRUD = new TipoCRUD();
        frmTipo appFormaTipo = new frmTipo();
        frmTipoTodo appTipoTodos = new frmTipoTodo(appFormaTipo, true);
        ControlTipo appControlTipo = new ControlTipo(appTipo, appTipoCRUD, appFormaTipo, appTipoTodos);
        appControlTipo.IniciarTipo();
        appFormaTipo.setVisible(true);
    }//GEN-LAST:event_jMenuTiposActionPerformed

    private void mnuOrdenTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOrdenTMouseClicked
        Cliente appCliente = new Cliente();
        Vehiculo appvehiculo = new Vehiculo();
        Marca appMarca = new Marca();
        Tipo appTipo = new Tipo();
        Color appColor = new Color();
        Repuesto appRepuesto = new Repuesto();
        RepuestoCRUD appRepuestoCRUD = new RepuestoCRUD();
        OrdenTrab appOrdenTrab = new OrdenTrab();
        OrdenTrabCRUD appOrdenTrabCRUD = new OrdenTrabCRUD();
        frmMantenimiento appFormaMtto = new frmMantenimiento();
        frmRepuTodo appRepuestoTodos = new frmRepuTodo(appFormaMtto, true);
        ControlOrdenTrab appControlOrdenTrab = new ControlOrdenTrab(appCliente,
                appvehiculo,
                appMarca,
                appTipo,
                appColor,
                appRepuesto,
                appRepuestoCRUD,
                appOrdenTrab,
                appOrdenTrabCRUD,
                appFormaMtto,
                appRepuestoTodos);
        appControlOrdenTrab.IniciarMtto();
        appFormaMtto.setVisible(true);
    }//GEN-LAST:event_mnuOrdenTMouseClicked

    private void mnuRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepuestoActionPerformed
        Repuesto appRepuesto = new Repuesto();
        RepuestoCRUD appRepuestoCRUD = new RepuestoCRUD();
        frmRepuesto appFormaRepuesto = new frmRepuesto();
        frmRepuTodo appRepuestoTodos = new frmRepuTodo(appFormaRepuesto, true);
        ControlRepuesto appControlRepuesto = new ControlRepuesto(appRepuesto, appRepuestoCRUD, appFormaRepuesto, appRepuestoTodos);
        appControlRepuesto.IniciarRepuesto();
        appFormaRepuesto.setVisible(true);
    }//GEN-LAST:event_mnuRepuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCiudades;
    private javax.swing.JMenuItem jMenuColor;
    private javax.swing.JMenuItem jMenuTipos;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu mnuCliente;
    public javax.swing.JMenuItem mnuMarca;
    public javax.swing.JMenu mnuOrdenT;
    public javax.swing.JMenuItem mnuRepuesto;
    public javax.swing.JMenu mnuVehiculo;
    // End of variables declaration//GEN-END:variables
}
