/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Chris
 */
public class frmRepuesto extends javax.swing.JFrame {

    /**
     * Creates new form frmMarca
     */
    public frmRepuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgRepuesto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCodRepu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescRepu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnValidarRepu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarRepu = new javax.swing.JButton();
        btnSalirRepu = new javax.swing.JButton();
        btnEditarRepu = new javax.swing.JButton();
        btnBuscarRepu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomRepu = new javax.swing.JTextField();
        spnCantRepu = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        cboTipoRepu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cod. Repuesto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 100, -1, -1));

        txtCodRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCodRepu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCodRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtDescRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtDescRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 295, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Stock");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        btnValidarRepu.setBackground(new java.awt.Color(102, 102, 102));
        btnValidarRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnValidarRepu.setForeground(new java.awt.Color(255, 255, 255));
        btnValidarRepu.setText(">>>");
        btnValidarRepu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnValidarRepu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnValidarRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 46, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setText("Gestión Repuesto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 55));

        btnGuardarRepu.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardarRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarRepu.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRepu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_save_16px.png"))); // NOI18N
        btnGuardarRepu.setText("Guardar");
        btnGuardarRepu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarRepu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnGuardarRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 116, -1));

        btnSalirRepu.setBackground(new java.awt.Color(102, 102, 102));
        btnSalirRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalirRepu.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirRepu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_close_window_16px.png"))); // NOI18N
        btnSalirRepu.setText("Salir");
        btnSalirRepu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalirRepu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalirRepu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRepuActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 116, -1));

        btnEditarRepu.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarRepu.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarRepu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_edit_property_16px.png"))); // NOI18N
        btnEditarRepu.setText("Modificar");
        btnEditarRepu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarRepu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnEditarRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 116, -1));

        btnBuscarRepu.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarRepu.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarRepu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_search_more_16px.png"))); // NOI18N
        btnBuscarRepu.setText("Buscar");
        btnBuscarRepu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarRepu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnBuscarRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 116, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_maintenance_96px.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 88));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtNomRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtNomRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 295, -1));

        spnCantRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spnCantRepu.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spnCantRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 50, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        cboTipoRepu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboTipoRepu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "      --- Seleccione ---", "MECANICO", "ELECTRICO" }));
        getContentPane().add(cboTipoRepu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirRepuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRepuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirRepuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRepuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgRepuesto;
    public javax.swing.JButton btnBuscarRepu;
    public javax.swing.JButton btnEditarRepu;
    public javax.swing.JButton btnGuardarRepu;
    public javax.swing.JButton btnSalirRepu;
    public javax.swing.JButton btnValidarRepu;
    public javax.swing.JComboBox<String> cboTipoRepu;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JSpinner spnCantRepu;
    public javax.swing.JTextField txtCodRepu;
    public javax.swing.JTextField txtDescRepu;
    public javax.swing.JTextField txtNomRepu;
    // End of variables declaration//GEN-END:variables
}
