/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Chris
 */
public class frmTipo extends javax.swing.JFrame {

    /**
     * Creates new form frmMarca
     */
    public frmTipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCodTipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        rbtActTipo = new javax.swing.JRadioButton();
        rbtInaTipo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsTipo = new javax.swing.JTextArea();
        btnValidarTipo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarTipo = new javax.swing.JButton();
        btnSalirTipo = new javax.swing.JButton();
        btnEditarTipo = new javax.swing.JButton();
        btnBuscarTipo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cod. Tipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtCodTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCodTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCodTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 109, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Descr. Tipo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 150, -1, -1));

        txtTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 146, 295, -1));

        btgTipo.add(rbtActTipo);
        rbtActTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtActTipo.setText("Activo");
        getContentPane().add(rbtActTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 181, -1, 30));

        btgTipo.add(rbtInaTipo);
        rbtInaTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtInaTipo.setText("Inactivo");
        getContentPane().add(rbtInaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 181, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Estado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 184, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Observaciones");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 217, -1, -1));

        txtObsTipo.setColumns(20);
        txtObsTipo.setRows(5);
        jScrollPane1.setViewportView(txtObsTipo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 217, 292, -1));

        btnValidarTipo.setBackground(new java.awt.Color(102, 102, 102));
        btnValidarTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnValidarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnValidarTipo.setText(">>>");
        btnValidarTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnValidarTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnValidarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 109, 46, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setText("Gestión Tipo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 55));

        btnGuardarTipo.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardarTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_save_16px.png"))); // NOI18N
        btnGuardarTipo.setText("Guardar");
        btnGuardarTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarTipo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnGuardarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 111, 116, -1));

        btnSalirTipo.setBackground(new java.awt.Color(102, 102, 102));
        btnSalirTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalirTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_close_window_16px.png"))); // NOI18N
        btnSalirTipo.setText("Salir");
        btnSalirTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalirTipo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 240, 116, -1));

        btnEditarTipo.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_edit_property_16px.png"))); // NOI18N
        btnEditarTipo.setText("Modificar");
        btnEditarTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarTipo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnEditarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 154, 116, -1));

        btnBuscarTipo.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_search_more_16px.png"))); // NOI18N
        btnBuscarTipo.setText("Buscar");
        btnBuscarTipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarTipo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnBuscarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 197, 116, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_automatic_96px.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 88));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgTipo;
    public javax.swing.JButton btnBuscarTipo;
    public javax.swing.JButton btnEditarTipo;
    public javax.swing.JButton btnGuardarTipo;
    public javax.swing.JButton btnSalirTipo;
    public javax.swing.JButton btnValidarTipo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton rbtActTipo;
    public javax.swing.JRadioButton rbtInaTipo;
    public javax.swing.JTextField txtCodTipo;
    public javax.swing.JTextArea txtObsTipo;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
