-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 17:49:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HotelJava
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HotelJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelJava` DEFAULT CHARACTER SET utf8 ;
USE `HotelJava` ;

-- -----------------------------------------------------
-- Table `HotelJava`.`tbHabitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbHabitacion` (
  `id_Habitacion` INT NOT NULL AUTO_INCREMENT,
  `numero_hab` VARCHAR(4) NOT NULL,
  `piso_hab` VARCHAR(3) NOT NULL,
  `descr_hab` VARCHAR(255) NULL,
  `caract_hab` VARCHAR(512) NULL,
  `precio_dia_hab` DECIMAL(18,2) NOT NULL,
  `estado_hab` VARCHAR(50) NOT NULL,
  `tipo_hab` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Habitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbPersona` (
  `id_Persona` INT NOT NULL AUTO_INCREMENT,
  `nombre_per` VARCHAR(100) NOT NULL,
  `prim_ape_per` VARCHAR(50) NOT NULL,
  `seg_ape_per` VARCHAR(50) NOT NULL,
  `tip_doc_per` VARCHAR(45) NOT NULL,
  `num_doc_per` VARCHAR(45) NOT NULL,
  `direccion_per` VARCHAR(100) NULL,
  `telefono_per` VARCHAR(45) NOT NULL,
  `email_per` VARCHAR(255) NULL,
  PRIMARY KEY (`id_Persona`),
  UNIQUE INDEX `email_per_UNIQUE` (`email_per` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbCliente` (
  `id_Persona` INT NOT NULL,
  `cod_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Persona`),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC),
  CONSTRAINT `FK_Persona_Cliente`
    FOREIGN KEY (`id_Persona`)
    REFERENCES `HotelJava`.`tbPersona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbTrabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbTrabajador` (
  `id_Persona` INT NOT NULL,
  `sueldo_trabj` DECIMAL(18,2) NOT NULL,
  `acceso_trabj` VARCHAR(45) NOT NULL,
  `login_trabj` VARCHAR(45) NOT NULL,
  `password_trabj` VARCHAR(45) NOT NULL,
  `estado_trabj` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_Persona`),
  UNIQUE INDEX `login_trabj_UNIQUE` (`login_trabj` ASC),
  CONSTRAINT `FK_Persona_Trabajador`
    FOREIGN KEY (`id_Persona`)
    REFERENCES `HotelJava`.`tbPersona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbProducto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_prod` VARCHAR(45) NOT NULL,
  `descr_prod` VARCHAR(255) NULL,
  `und_med_prod` VARCHAR(45) NOT NULL,
  `val_venta_prod` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`id_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbReserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbReserva` (
  `id_Reserva` INT NOT NULL AUTO_INCREMENT,
  `id_habitacion` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_trabajador` INT NOT NULL,
  `tipo_reserva` VARCHAR(45) NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `fec_ing_cliente` DATE NOT NULL,
  `fec_sale_cliente` DATE NOT NULL,
  `costo_tot_aloj` DECIMAL(18,2) NOT NULL,
  `estado_reserva` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Reserva`),
  INDEX `FK_Reserva_Habitacion_idx` (`id_habitacion` ASC),
  INDEX `FK_Reserva_Cliente_idx` (`id_cliente` ASC),
  INDEX `FK_Reserva_Trabajador_idx` (`id_trabajador` ASC),
  CONSTRAINT `FK_Reserva_Habitacion`
    FOREIGN KEY (`id_habitacion`)
    REFERENCES `HotelJava`.`tbHabitacion` (`id_Habitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Reserva_Cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `HotelJava`.`tbCliente` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Reserva_Trabajador`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `HotelJava`.`tbTrabajador` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbConsumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbConsumo` (
  `id_Consumo` INT NOT NULL AUTO_INCREMENT,
  `id_Reserva` INT NOT NULL,
  `id_Producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(18,2) NOT NULL,
  `estado_cons` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Consumo`),
  INDEX `FK_Consumo_Producto_idx` (`id_Producto` ASC),
  INDEX `FK_Consumo_Reserva_idx` (`id_Reserva` ASC),
  CONSTRAINT `FK_Consumo_Producto`
    FOREIGN KEY (`id_Producto`)
    REFERENCES `HotelJava`.`tbProducto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Consumo_Reserva`
    FOREIGN KEY (`id_Reserva`)
    REFERENCES `HotelJava`.`tbReserva` (`id_Reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelJava`.`tbPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelJava`.`tbPago` (
  `id_Pago` INT NOT NULL AUTO_INCREMENT,
  `id_Reserva` INT NOT NULL,
  `tipo_comprobante` VARCHAR(45) NOT NULL,
  `num_comprobante` VARCHAR(45) NOT NULL,
  `iva_pago` DECIMAL(18,2) NOT NULL,
  `total_pago` DECIMAL(18,2) NOT NULL,
  `fec_gen_comprobante` DATE NOT NULL,
  `fec_pago` DATE NOT NULL,
  PRIMARY KEY (`id_Pago`),
  INDEX `FK_Pago_Reserva_idx` (`id_Reserva` ASC),
  CONSTRAINT `FK_Pago_Reserva`
    FOREIGN KEY (`id_Reserva`)
    REFERENCES `HotelJava`.`tbReserva` (`id_Reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
